version: "1.0"

stages:
  - clone
  - build
  - push
  - test

steps:
  main_clone:
    title: Cloning repository...
    stage: clone
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
  build:
    title: Building Docker Image...
    stage: build
    type: build
    image_name: cf-utils
    tag: 'latest'
    dockerfile: Dockerfile.cf-utils
    disable_push: true
  test:
    title: Testing Docker Image...
    stage: test
    image: aprart-docker.artifactory.gcp.anz/cf-utils:0.0.2
    commands:
      - terraform --version
      - aws --version
      - python --version
